[package]
name = "dprint"
version = "0.9.1"
authors = ["Dprint Code Formatting <david@dprint.dev>"]
edition = "2018"
license-file = "LICENSE"
description = "Binary for dprint."
repository = "https://github.com/dprint/dprint"

[dependencies]
clap = "2.33.0"
crossterm = "0.18.0"
dunce = "1.0.1"
dprint-core = { path = "../core", version = "0.32.0", features = ["process", "wasm"] }
dprint-cli-core = { path = "../cli-core", version = "0.5.1" }
dissimilar = "1.0"
globwalk = "0.8.0"
jsonc-parser = { version = "0.14.0" }
parking_lot = "0.11.0"
dirs = "3.0.1"
num_cpus = "1.13.0"
rayon = "1.4.1"
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0"
twox-hash = "1.5.0"
url = "2.1.1"
wasmer = "1.0.0-alpha4"
zip = "0.5.8"

[dev-dependencies]
globset = "0.4.5"
lazy_static = "1.4.0"
pretty_assertions = "0.6.1"
path-clean = "0.1.0"
